name: Test Dispatch

on:
  workflow_dispatch:
    inputs:
      test:
        description: 'test input'
        required: false

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - run: echo 'Hello from test workflow'
